"""empty message

Revision ID: 6f5c61641c35
Revises: af67c803c17f
Create Date: 2017-11-18 10:36:40.060256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5c61641c35'
down_revision = 'af67c803c17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('bucketlists', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlists', 'date_modified')
    op.drop_column('bucketlists', 'date_created')
    # ### end Alembic commands ###
