"""empty message

Revision ID: 8590330ed0a3
Revises: 56c377280012
Create Date: 2017-10-07 17:15:29.123120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8590330ed0a3'
down_revision = '56c377280012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlists_owner_fkey', 'bucketlists', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlists', 'users', ['owner'], ['id'], ondelete='cascade')
    op.drop_constraint('items_bucketlist_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'bucketlists', ['bucketlist_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_bucketlist_id_fkey', 'items', 'bucketlists', ['bucketlist_id'], ['id'])
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.create_foreign_key('bucketlists_owner_fkey', 'bucketlists', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###
