"""empty message

Revision ID: 95a58fa49655
Revises: f65cd9a4ae76
Create Date: 2017-09-09 22:54:27.288985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a58fa49655'
down_revision = 'f65cd9a4ae76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_token', sa.Column('token', sa.String(), nullable=False))
    op.drop_constraint('blacklist_token_tokken_key', 'blacklist_token', type_='unique')
    op.create_unique_constraint(None, 'blacklist_token', ['token'])
    op.drop_column('blacklist_token', 'tokken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_token', sa.Column('tokken', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blacklist_token', type_='unique')
    op.create_unique_constraint('blacklist_token_tokken_key', 'blacklist_token', ['tokken'])
    op.drop_column('blacklist_token', 'token')
    # ### end Alembic commands ###
